;;; Window related defuns
(defun defuns-windows-rotate-windows (count)
  "Rotate your windows"
  (interactive "p")
  (let* ((ws (window-list))
         (bs (mapcar 'window-buffer ws))
         (ss (mapcar 'window-start ws))
         (i 0)
         (n (count-windows))
         )
    (while (< i n)
      (let* ((w (elt ws i))
             (j (mod (+ i count) n))
             (b (elt bs j))
             (s (elt ss j))
             )
        (set-window-buffer w b)
        (set-window-start w s)
        )
      (setq i (+ i 1))
      )
    )
  )

(provide 'defuns-windows)
