;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-kill-sentence
        c-electric-colon
        c-electric-delete-forward
        c-electric-paren
        c-electric-pound
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-indent-line-or-region
        electric-newline-and-maybe-indent
        erlang-electric-comma
        evil-numbers/dec-at-pt
        evil-numbers/inc-at-pt
        haskell-indentation-delete-char
        indent-for-tab-command
        kill-or-join-next-line
        kmacro-end-or-call-macro
        kmacro-start-macro-or-insert-counter
        markdown-exdent-or-delete
        mc-search-backward
        mc-search-forward
        nav-forward-blank-line
        nav-half-page-down
        nav-half-page-up
        nav-next-line
        nav-previous-line
        prelude-move-beginning-of-line
        smex
        subword-left
        subword-right
        whole-line-or-region-kill-region
        whole-line-or-region-kill-ring-save
        whole-line-or-region-yank
        ))

(setq mc/cmds-to-run-once
      '(
        ))
